<?php
/**
 * @file at_pdb.module
 */

/**
 * Implements hook_permission().
 */
function at_pdb_permission() {
  return array(
    'access phpdebugbar' => array(
      'title' => 'access phpdebugbar',
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_pdb_page_alter()
 */
function at_pdb_page_alter(&$page) {
  if (user_access('access phpdebugbar')) {
    at_container('at_pdb.page_alter')
      ->setPage($page)
      ->execute();
  }
}
